const CHANGE_NAME = 'CHANGE_NAME'
const CHANGE_ZIP_CODE = 'CHANGE_ZIP_CODE'
const CHANGE_ADDRESS = 'CHANGE_ADDRESS'
const CLEAR_ALL = 'CLEAR_ALL'


module.exports = {
    CHANGE_NAME,
    CHANGE_ZIP_CODE,
    CHANGE_ADDRESS,
    CLEAR_ALL
}
